### ISSUE TITLE
Files sent in chat window

### ISSUE THREAD

**Issue by pporlan** [igniterealtime/Spark#20]
Files that have been sent don't appear in the conversation area of the chat window if you close and open it later.
I don't know if this is a bug exactly or the normal behaviour.

**Comment by wrooot** [comment]
This is "by design". File transfer is not a message, so it is not saved in the conversation history and when you re-open a window, it only loads what's in the conversation history. So in Spark file transfer messages are temporary. Btw, it's better to post in the forums https://community.igniterealtime.org/welcome
